- src/shared/components/Button/Button.module.scss
- src/shared/components/Button/Button.stories.tsx
- src/shared/components/Button/Button.tsx
- 공통 버튼 컴포넌트 추가
- 스토리북 링크: https://sullog-official.github.io/sullog-client/?path=/docs/shared-components-button--docs
> [Feature] shared/Button 컴포넌트 추가

- src/assets/styles/themes/_z-index.module.scss
- src/shared/components/Drawer/Drawer.module.scss
- src/shared/components/Drawer/Drawer.stories.tsx
- src/shared/components/Drawer/Drawer.tsx
- src/shared/components/Drawer/index.ts
> [Feature] Drawer 컴포넌트 추가

- .stylelintrc.json
- .vscode/settings.json
- src/assets/styles/_mixins.module.scss
- src/assets/styles/global.scss
- src/assets/styles/reset.scss
- src/assets/styles/themes/_color.module.scss
- src/assets/styles/themes/_typography.module.scss
- src/assets/styles/themes/theme-story.module.scss
- src/features/record/FlavorSliderGroup/FlavorSliderGroup.module.scss
- src/features/record/Rating/Rating.module.scss
- src/shared/components/BottomNavigator/BottomNavigator.module.scss
- src/shared/components/Button/Button.module.scss
- src/shared/components/Chip/Chip.module.scss
- src/shared/components/Drawer/Drawer.module.scss
- src/shared/components/Icon/Icon.module.scss
- src/shared/components/Slider/Slider.module.scss
- src/shared/components/TextField/TextField.module.scss
- vscode workspace setting 추가
- stylelintrc rules 추가
- 변경된 rules 기반으로 scss 파일 수정
> [FIX] stylelint

- src/shared/components/TextField/TextField.module.scss
- src/shared/components/TextField/TextField.stories.tsx
- src/shared/components/TextField/TextField.tsx
- `<span>` -> `<label>`
- remove `gap` property
- change `editable` -> `disabled`
> fix: TextField

- src/features/record/Accordion/Accordion.module.scss
- src/features/record/Accordion/Accordion.stories.tsx
- src/features/record/Accordion/Accordion.tsx
- src/features/record/Accordion/index.ts
- 일단 컴포넌트 구현하기했는데, 칩들 사이의 간격을 어떤 css로 조정해야하는지 모르겠네요ㅜㅜ 도움바랍니다
> [Feature] Accordion 컴포넌트 구현

- next.config.js
- src/assets/icons/back.svg
- src/assets/icons/index.ts
- src/features/search/AlcoholCategoryTab/AlcoholCategoryTab.module.scss
- src/features/search/AlcoholCategoryTab/AlcoholCategoryTab.stories.tsx
- src/features/search/AlcoholCategoryTab/AlcoholCategoryTab.tsx
- src/features/search/AlcoholCategoryTab/index.ts
- src/features/search/AlcoholCategoryTabItem/AlcoholCategoryTabItem.module.scss
- src/features/search/AlcoholCategoryTabItem/AlcoholCategoryTabItem.tsx
- src/pages/list/List.module.scss
- src/pages/list/List.tsx
- src/pages/list/index.ts
- src/shared/components/BottomNavigator/BottomNavigator.module.scss
- src/shared/components/BottomNavigator/BottomNavigator.tsx
- src/shared/components/TopNavigator/TopNavigator.module.scss
- src/shared/components/TopNavigator/TopNavigator.stories.tsx
- src/shared/components/TopNavigator/TopNavigator.tsx
- src/shared/components/TopNavigator/index.ts
- 리스트 페이지를 작업하였습니다.
- 카테고리 선택 별로 아이콘의 색깔이 변하는 기능을 추가하였습니다.
- ex. 강남구 테헤란로와 같은 지역 클러스터링에 대한 논의가 필요합니다.
- 상단 네비게이션 공통 컴포넌트가 필요합니다.
- 상단 네비게이션 컴포넌트 구현하였습니다.
- 해당 페이지에서 테스트해보느라 같은 브랜치에서 작업했습니다.
> [Feature] 리스트 페이지

- src/assets/styles/themes/_typography.module.scss
- src/shared/components/TextArea/TextArea.module.scss
- src/shared/components/TextArea/TextArea.stories.tsx
- src/shared/components/TextArea/TextArea.tsx
- src/shared/components/TextArea/index.ts
> [Feature] TextArea 공통 컴포넌트 추가

- src/features/record/AbvInput/AbvInput.module.scss
- src/features/record/AbvInput/AbvInput.stories.tsx
- src/features/record/AbvInput/AbvInput.tsx
- src/features/record/AbvInput/index.ts
- src/features/record/DetailFlavorInput/DetailFlavorInput.module.scss
- src/features/record/DetailFlavorInput/DetailFlavorInput.stories.tsx
- src/features/record/DetailFlavorInput/DetailFlavorInput.tsx
- src/features/record/DetailFlavorInput/index.ts
- src/features/record/FlavorSliderGroup/FlavorSliderGroup.module.scss
- src/features/record/FlavorSliderGroup/FlavorSliderGroup.tsx
- src/features/record/Rating/Rating.module.scss
- src/features/record/Rating/Rating.stories.tsx
- src/features/record/Rating/Rating.tsx
- src/pages/records/create/index.module.scss
- src/pages/records/create/index.tsx
- src/shared/components/TextArea/TextArea.module.scss
- src/shared/components/TextArea/TextArea.tsx
- src/shared/components/TextField/TextField.module.scss
- src/shared/components/TextField/TextField.stories.tsx
- src/shared/components/TextField/TextField.tsx
- TextField 리팩토링
- placeHolder 스타일 설정
- prop 타입 수정
- span 대신 label 태그 사용
- Rating, FlavorSliderGroup 컴포넌트 label 속성 추가
- AbvInput 컴포넌트 추가
- 알콜 도수가 영어로 ABV라고해서 이렇게 지었습니다.
- (추후 백엔드에 넘겨주는 네이밍으로 수정하면 좋을 것 같습니다)
- DetailFlavorInput 컴포넌트 추가
- TextArea 컴포넌트 수정
- label 추가
- font-size 수정
- 글쓰기 페이지 마크업 -> react-hook-form을 미리 적용할까 했지만, 
도수나 플레이버 같은 경우 아직 입력 형식도 미정인 상태라 추후 기능 구현때 하는 것이 좋을 것 같습니다!
> [Feature] 기록하기 페이지

- src/features/search/RecentSearches/RecentSearches.module.scss
- src/features/search/RecentSearches/RecentSearches.tsx
> [FIX] RecentSearches

- src/shared/configs/axios.ts
> [FIX] axios error

- src/shared/apis/alcohols/getAlcohol.ts
- src/shared/apis/records/createRecord.ts
- src/shared/apis/records/getRecord.ts
- src/shared/types/alcohol.ts
- src/shared/types/record/alcoholPercentFeeling.ts
- src/shared/types/record/flavorTag.ts
- src/shared/types/record/index.ts
- src/shared/utils/request.ts
- record, alcohol 타입 추가
- request util 함수 추가
- useCreateRecord, useGetRecord, useGetAlcohol 훅 추가
> feat: record 생성 관련 api 타입, 훅 추가

- src/assets/styles/global.scss
- src/features/feed/components/Card/Card.module.scss
- src/features/feed/components/Card/Card.stories.tsx
- src/features/feed/components/Card/Card.tsx
- src/features/feed/components/Card/index.ts
- src/pages/feed/index.module.scss
- src/pages/feed/index.tsx
- src/shared/components/BottomNavigator/BottomNavigator.tsx
- 둘러보기 페이지를 개발했습니다.
- 스크롤을 안보이게 할까 생각했었는데, 접근성에 문제가 있을까 생각도 들어서 일단은 두었습니다. 스크롤의 width 때문에 화면이 살짝 왼쪽으로 밀리지만 모바일 화면에서는 안 보일 것 같습니다.
- 현재는 placeholder 이미지로 모킹하였습니다. 샘플 데이터를 넣어달라고 요청드렸고 완료되면 데이터가 없을 때의 화면도 개발하겠습니다.
- 스켈레톤 UI도 그 때 넣겠습니다.
> [FEATURE] 둘러보기 페이지 개발

- src/features/feed/components/Card/Card.tsx
- src/pages/feed/index.tsx
- src/shared/apis/feed/getFeed.ts
- src/shared/types/feed/index.ts
- src/shared/types/paging.ts
피드 페이지를 1차 구현했습니다. 무한 스크롤 적용 전에 PR 올립니다.
무한 스크롤에 활용할 수 있는 라이브러리가
- react-use의 useIntersection
- react-intersection-observer
이렇게 있는데 어떤걸 사용하는게 좋은지 조언 구합니다.
> [FEATURE] 피드 페이지 구현

- src/pages/login/index.tsx
- src/shared/apis/auth/kakaoLogin.ts
- src/shared/configs/axios.ts
- accessToken 또는 refreshToken에 'undefined' 문자열이 들어가서 발생하던 문제를 해결했습니다.
> [FIX] token refreshing

- src/shared/components/Skeleton/Skeleton.module.scss
- src/shared/components/Skeleton/Skeleton.stories.tsx
- src/shared/components/Skeleton/Skeleton.tsx
- src/shared/components/Skeleton/index.ts
-  Skeleton 컴포넌트 추가 (resolve #77)
스토리북: https://sullog-official.github.io/sullog-client/?path=/docs/shared-components-skeleton--docs
> feat: Skeleton 컴포넌트 추가

- src/pages/feed/index.tsx
- https://github.com/liaoliao666/react-query-kit 를 참고하여 prefetchQuery -> prefetchInfiniteQuery로 교체하였습니다.
> [REFACTOR] prefetchInfiniteQuery로 교체

- src/assets/styles/global.scss
- src/assets/styles/themes/_index.scss
- src/assets/styles/themes/_layout.module.scss
- src/features/search/components/AlcoholCategoryTab/AlcoholCategoryTab.module.scss
- src/features/search/components/RecentSearches/RecentSearches.module.scss
- src/pages/alcohols/search/index.module.scss
- src/pages/alcohols/search/index.tsx
- src/pages/feed/index.module.scss
- src/pages/feed/index.tsx
- src/pages/index.module.scss
- src/pages/index.tsx
- src/pages/login/index.module.scss
- src/pages/login/index.tsx
- src/pages/my/records/index.module.scss
- src/pages/my/records/index.tsx
- src/pages/my/records/search/index.module.scss
- src/pages/my/records/search/index.tsx
- src/pages/records/[id]/index.tsx
- src/pages/records/create/index.tsx
- src/shared/components/BottomNavigator/BottomNavigator.module.scss
- src/shared/components/PageLayout/PageLayout.module.scss
- src/shared/components/PageLayout/PageLayout.tsx
- src/shared/components/PageLayout/index.ts
- src/shared/components/TopNavigator/TopNavigator.module.scss
- src/shared/components/TopNavigator/TopNavigator.tsx
resolve #76
- PageLayout 추가
- global.scss 수정
- BottomNavigation safe-area 대응
- TopNavigation children prop 추가
- 전체 페이지 레이아웃 리팩터링
- 모바일 최적화 된 디자인이므로 최대 너비를 530px로 고정했습니다.
> feat: PageLayout 추가 및 전체 페이지 레이아웃 리팩터링

- src/features/home/components/DrawerContents/DrawerContents.module.scss
- src/features/home/components/DrawerContents/DrawerContents.tsx
- src/shared/components/BottomNavigator/BottomNavigator.module.scss
- src/shared/components/BottomNavigator/BottomNavigator.tsx
- src/shared/components/Drawer/Drawer.module.scss
- src/shared/components/Drawer/Drawer.tsx
- src/shared/components/PageLayout/PageLayout.module.scss
> fix: Drawer ui 깨짐 수정

- next.config.js
- src/pages/feed/index.tsx
- src/pages/records/[id]/index.tsx
- src/shared/configs/logger.ts
- 로깅시 multipart/form-data를 파싱하는 경우 에러가 나서 수정
- next.config.js에 이미지 경로를 특정하도록 수정
- 이웃 피드 클릭시 상세페이지로 이동
axios 또는 react query 에서 응답 location을 받아오는 방법 아시는 분 계신가요?
react query의 onSuccess 시 context와 axios response.header 확인해봤는데, 실패해서 도움 요청합니다!
-> BE 협의 후 별도 pr로 반영 예정
> feat: 피드 클릭 후 상세페이지 이동 및 자잘한 버그 수정

- src/assets/styles/fonts/index.ts
- `display: 'swap'`을 추가했습니다.
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
> [FIX] 로컬 폰트가 로드되지 않는 이슈

- src/pages/feed/index.tsx
- isFetching에 맞춰 두 칸의 스켈레톤 컴포넌트를 추가하였습니다.
> [FEATURE] Skeleton 추가

- src/pages/login/index.module.scss
- src/pages/login/index.tsx
- position absolute로 반투명한 UI를 주었습니다.
> [FEATURE] 로그인 시 토큰 세팅하는 UI

- src/features/record/hooks/useCreateRecordForm.ts
- src/shared/apis/records/createRecord.ts
> feat: 기록 생성 후 생성된 기록 화면으로 이동

- .pnp.cjs
- package.json
- yarn.lock
https://storybook.js.org/docs/react/writing-tests/test-runner을 참고하여 세팅하였습니다.
`yarn test-storybook` 명령어로 모든 스토리북을 테스트합니다.
> [FEATURE] 스토리북을 이용한 UI 테스트

- src/features/home/components/Map/Map.tsx
- src/pages/index.tsx
- src/shared/types/alcohol.ts
- 필터 클릭 시 alcohol 카드 숨기기
- 필터 클릭 시 해당 주종에 해당하는 기록만 표시
현재 백엔드 이슈로 두 번째 수정사항은 확인 불가능해서 수정되고 확인되면 머지할게요
> fix: 홈 주종 필터 수정

- src/features/home/components/DrawerContents/DrawerContents.tsx
> feat: mailto

- src/shared/components/Button/Button.module.scss
- src/shared/components/Chip/Chip.module.scss
Chip Primary 스타일에 border를 추가하여 클릭 시 칩이 작아지는 버그를 수정하였습니다.
> style: Primary 스타일에 border 추가

- src/features/home/components/Map/Map.module.scss
- src/pages/index.tsx
- src/shared/components/Drawer/Drawer.module.scss
````css
position: fixed;
height: 100vh;
width: 100%;
bottom: env(safe-area-inset-bottom);
````
지도 하단에 env(safe-area-inset-bottom)으로 offset을 두었습니다
> fix: safari 하단바 이슈

- src/pages/feed/index.tsx
- src/pages/index.tsx
- src/shared/components/BottomNavigator/BottomNavigator.tsx
- 피드 페이지에서 바텀 네비게이터 아이콘 색상이 바뀌었습니다.
> feat: 바텀 네비게이터 아이콘 색상 변경

- src/features/home/components/Slider/Slider.tsx
- src/pages/index.tsx
- src/shared/types/alcohol.ts
- alcoholTag -> alcoholType 로의 변경을 반영했습니다.
> fix: reflect api changes

- src/features/search/components/AlcoholCategoryTab/AlcoholCategoryTab.tsx
- src/features/search/components/AlcoholCategoryTabItem/AlcoholCategoryTabItem.tsx
- src/pages/index.tsx
- src/pages/my/records/index.tsx
- src/shared/types/alcohol.ts
- api 연동 후 필터 기능 구현했습니다.
- 이전 PR과 함께 필터하는 함수 공통으로 만들어서 사용하겠습니다.
> fix: /my/records/ api 연동 누락

- src/features/home/components/Map/Map.module.scss
- src/pages/index.tsx
> fix: 지도가 화면 넓이를 넘치는 문제 수정

- src/features/search/components/SearchBar/SearchBar.module.scss
- src/pages/index.tsx
> fix: input 글자 잘림

- src/features/search/components/SearchBar/SearchBar.tsx
input 요소에 autofocus 속성을 true로 설정하여 검색 모달이 올라왔을 때 검색바에 auto focusing이 되게 하였습니다.
> feat: input autofocus

- src/assets/styles/global.scss
- src/features/home/components/Map/Map.module.scss
> fix: prevent scroll in safari

- src/pages/records/create/index.tsx
@syoung125 님이 만들어주신 엄청난 컨펌 모달 덕분에 버스 탔습니다. 모달 대박이네요 많이 배우겠습니다 감사합니다  ^^
> feat: 경험 기록 도중 뒤로가기 클릭 시 컨펌 모달 보여줌

- src/assets/styles/global.scss
- src/features/search/components/AlcoholSearchModal/AlcoholSearchModal.tsx
- src/features/search/components/MyRecordSearchModal/MyRecordSearchModal.tsx
- src/shared/components/Drawer/Drawer.module.scss
- src/shared/components/PageLayout/PageLayout.module.scss
- src/shared/components/PageLayout/PageLayout.tsx
> fix: 이슈 해결

- src/pages/records/create/index.tsx
- react-hook-form의 isSubmitting 속성을 이용하여 버튼을 disabled 하였습니다.
> feat: 폼 제출 도중에 disabled 속성 추가

- src/features/alcohol/components/AlcoholPreview/AlcoholPreview.module.scss
- src/features/home/components/Slider/Slider.module.scss
- src/features/home/components/Slider/Slider.tsx
- 클릭 시 해당하는 상세 경험 페이지로 이동
- 클릭 시 /my/records로 이동
> fix: 누락된 링크 연결

- src/features/record/components/FlavorSliderGroup/FlavorSliderGroup.tsx
- src/features/record/hooks/useCreateRecordForm.ts
#174 에서 useForm 훅 내부 defaultValues 값 수정으로  대응하니 잘 동작하는 것 같습니다!
@shinwonse
> fix: Flavor Slider 기본값 없는 경우 값이 있는 상태로 인식 못하는 에러 수정

- src/features/search/components/MyRecordSearchModal/MyRecordSearchModal.tsx
- src/features/search/components/RecentSearches/RecentSearches.tsx
- 최근 검색어를 하나 지워도 클릭 영역이 잘못되어 지워지지 않는 이슈 해결
- 검색 키워드가 비어있을 때 최근 검색어를 보여주게 수정
> fix: 최근 검색어 오류 수정

- src/features/search/components/MyRecordSearchResult/MyRecordSearchResult.module.scss
- src/features/search/components/MyRecordSearchResult/MyRecordSearchResult.tsx
- src/shared/apis/records/searchMyRecords.ts
- cursor의 디폴트 값이 null이어야 해서 수정했습니다.
- 카드간의 간격을 주었습니다.
> fix: 나의 경험 검색이 안되던 버그 픽스 및 스타일 수정

- src/features/home/components/Slider/Slider.module.scss
- src/features/home/components/Slider/Slider.tsx
- src/shared/configs/axios.ts
> fix: slider styles

- src/features/search/components/MyRecordSearchModal/MyRecordSearchModal.tsx
- src/features/search/components/MyRecordSearchResult/MyRecordSearchResult.tsx
- src/features/search/hooks/useMyRecentSearchKeywords.ts
- src/shared/apis/me/saveMyRecentSearchKeyword.ts
- `useMyRecentSearchKeyword` 훅에 save 관련 로직을 넣었습니다.
> fix: 나의 술 경험 검색에서 실제로 검색 결과를 클릭해야만 검색 결과가 저장되도록 함

- src/features/alcohol/components/AlcoholPreview/AlcoholPreview.module.scss
> 술이름, 브랜드 두 줄로 표현

- src/features/home/components/DrawerContents/DrawerContents.module.scss
- src/features/home/components/DrawerContents/DrawerContents.tsx
- src/shared/apis/auth/delete.ts
- Drawer 안에 로그아웃 버튼 아래에 회원탈퇴 버튼을 개발했습니다.
- confirm을 띄우도록 했습니다.
> feat: 회원 탈퇴 기능 개발
